# Site settings
title: Minimal Staticman v3 Demo
url: "https://vincenttam.github.io/TestStaticmanLab/"

staticman:
  api: "https://anasbasem.herokuapp.com/v2/entry/basemwahba/rana/master/comments"
  path: "_data/comments"
